In [4]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

pd.set_option('display.max_columns',1000)
pd.set_option('display.max_rows',1000)

In [30]:
def restructure_event_data():
    event_df = pd.read_csv('data/custom/retrosheet_events.csv', index_col=[0,1])
    event_df.drop(columns=[
        'date', 'game_num', 'misc', 'acquisition_info', 'visiting_team_game_num', 'home_team_game_num',
        'completion_info', 'forfeit_info', 'protest_info', 'visiting_line_score',
        'home_line_score', 'ump_home_name', 'ump_first_name', 'ump_second_name',
        'ump_third_name', 'ump_lf_name', 'ump_rf_name', 'visiting_manager_name',
        'home_manager_name', 'winning_pitcher_id', 'winning_pitcher_name', 'losing_pitcher_id',
        'losing_pitcher_name', 'save_pitcher_id', 'save_pitcher_name', 'game_winning_rbi_id',
        'game_winning_rbi_name', 
    ], axis=1, inplace=True)
    event_df.rename(columns={
        'visiting_team': 'team_v',
        'visiting_team_league': 'league_v',
        'home_team': 'team_h',
        'home_team_league': 'league_h',
        'visiting_score': 'runs_v',
        'home_score': 'runs_h',
        'time_of_game_minutes': 'duration',
        # visiting team stats
        'visiting_abs': 'AB_v',
        'visiting_hits': 'H_v',
        'visiting_doubles': 'x2B_v',
        'visiting_triples': 'x3B_v',
        'visiting_homeruns': 'HR_v',
        'visiting_rbi': 'RBI_v',
        'visiting_sac_hits': 'sac_hits_v',
        'visiting_sac_flies': 'sac_flies_v',
        'visiting_hbp': 'HBP_v',
        'visiting_bb': 'BB_v',
        'visiting_iw': 'IBB_v',
        'visiting_k': 'K_v',
        'visiting_sb': 'SB_v',
        'visiting_cs': 'CS_v',
        'visiting_gdp': 'GDP_v',
        'visiting_ci': 'CI_v',
        'visiting_lob': 'LOB_v',
        'visiting_pitchers_used': 'num_pitchers_v',
        'visiting_individual_er': 'IER_v',
        'visiting_er': 'ER_v',
        'visiting_wp': 'WP_v',
        'visiting_balks': 'balks_v',
        'visiting_po': 'PO_v',
        'visiting_assists': 'assists_v',
        'visiting_errors': 'ERR_v',
        'visiting_pb': 'PB_v',
        'visiting_dp': 'x2P_v',
        'visiting_tp': 'x3P_v',
        'visiting_starting_pitcher_id': 'starting_pitcher_id_v',
        'visiting_starting_pitcher_name': 'starting_pitcher_name_v',
        'visiting_1_id': 'batter1_id_v',
        'visiting_2_id': 'batter2_id_v',
        'visiting_3_id': 'batter3_id_v',
        'visiting_4_id': 'batter4_id_v',
        'visiting_5_id': 'batter5_id_v',
        'visiting_6_id': 'batter6_id_v',
        'visiting_7_id': 'batter7_id_v',
        'visiting_8_id': 'batter8_id_v',
        'visiting_9_id': 'batter9_id_v',
        'visiting_1_name': 'batter1_name_v',
        'visiting_2_name': 'batter2_name_v',
        'visiting_3_name': 'batter3_name_v',
        'visiting_4_name': 'batter4_name_v',
        'visiting_5_name': 'batter5_name_v',
        'visiting_6_name': 'batter6_name_v',
        'visiting_7_name': 'batter7_name_v',
        'visiting_8_name': 'batter8_name_v',
        'visiting_9_name': 'batter9_name_v',
        'visiting_1_pos': 'batter1_pos_v',
        'visiting_2_pos': 'batter2_pos_v',
        'visiting_3_pos': 'batter3_pos_v',
        'visiting_4_pos': 'batter4_pos_v',
        'visiting_5_pos': 'batter5_pos_v',
        'visiting_6_pos': 'batter6_pos_v',
        'visiting_7_pos': 'batter7_pos_v',
        'visiting_8_pos': 'batter8_pos_v',
        'visiting_9_pos': 'batter9_pos_v',
        'visiting_manager_id': 'manager_v',
        # home team stats
        'home_abs': 'AB_h',
        'home_hits': 'H_h',
        'home_doubles': 'x2B_h',
        'home_triples': 'x3B_h',
        'home_homeruns': 'HR_h',
        'home_rbi': 'RBI_h',
        'home_sac_hits': 'sac_hits_h',
        'home_sac_flies': 'sac_flies_h',
        'home_hbp': 'HBP_h',
        'home_bb': 'BB_h',
        'home_iw': 'IBB_h',
        'home_k': 'K_h',
        'home_sb': 'SB_h',
        'home_cs': 'CS_h',
        'home_gdp': 'GDP_h',
        'home_ci': 'CI_h',
        'home_lob': 'LOB_h',
        'home_pitchers_used': 'num_pitchers_h',
        'home_individual_er': 'IER_h',
        'home_er': 'ER_h',
        'home_wp': 'WP_h',
        'home_balks': 'balks_h',
        'home_po': 'PO_h',
        'home_assists': 'assists_h',
        'home_errors': 'ERR_h',
        'home_pb': 'PB_h',
        'home_dp': 'x2P_h',
        'home_tp': 'x3P_h',
        'home_starting_pitcher_id': 'SP_h',
        'home_starting_pitcher_id': 'starting_pitcher_id_h',
        'home_starting_pitcher_name': 'starting_pitcher_name_h',
        'home_1_id': 'batter1_id_h',
        'home_2_id': 'batter2_id_h',
        'home_3_id': 'batter3_id_h',
        'home_4_id': 'batter4_id_h',
        'home_5_id': 'batter5_id_h',
        'home_6_id': 'batter6_id_h',
        'home_7_id': 'batter7_id_h',
        'home_8_id': 'batter8_id_h',
        'home_9_id': 'batter9_id_h',
        'home_1_name': 'batter1_name_h',
        'home_2_name': 'batter2_name_h',
        'home_3_name': 'batter3_name_h',
        'home_4_name': 'batter4_name_h',
        'home_5_name': 'batter5_name_h',
        'home_6_name': 'batter6_name_h',
        'home_7_name': 'batter7_name_h',
        'home_8_name': 'batter8_name_h',
        'home_9_name': 'batter9_name_h',
        'home_1_pos': 'batter1_pos_h',
        'home_2_pos': 'batter2_pos_h',
        'home_3_pos': 'batter3_pos_h',
        'home_4_pos': 'batter4_pos_h',
        'home_5_pos': 'batter5_pos_h',
        'home_6_pos': 'batter6_pos_h',
        'home_7_pos': 'batter7_pos_h',
        'home_8_pos': 'batter8_pos_h',
        'home_9_pos': 'batter9_pos_h',
        'home_manager_id': 'manager_h',
    }, inplace=True)
    event_df.rename(columns={'Season': 'season'}, inplace=True)
    return event_df

In [31]:
# strip away suffix, e.g., '_h', '_v', for given column
def strip_suffix(col, suffix):
    return col[:-len(suffix)] if col.endswith(suffix) else col

In [32]:
df = restructure_event_data()

visiting_cols = [col for col in df.columns if not col.endswith('_h')]
visiting_cols_stripped = [strip_suffix(col, '_v') for col in visiting_cols]
home_cols = [col for col in df.columns if not col.endswith('_v')]
home_cols_stripped = [strip_suffix(col, '_h') for col in home_cols]

/var/folders/y0/_yc3t8mn3kx8j1td1w609rl00000gn/T/ipykernel_72366/4231296234.py:2: DtypeWarning: Columns (15,16,17,87,89) have mixed types. Specify dtype option on import or set low_memory=False.
  event_df = pd.read_csv('data/custom/retrosheet_events.csv', index_col=[0,1])

In [33]:
windows = [162, 90, 30]

# create team dataframe to easily aggregate rolling window game data
def create_team_df(team):
    df_team_v = df[(df.team_v == team)]
    opp = df_team_v['team_h']
    df_team_v = df_team_v[visiting_cols]
    df_team_v.columns = visiting_cols_stripped
    df_team_v['home_game'] = 0
    df_team_v['opponent'] = opp
    
    df_team_h = df[(df.team_h == team)]
    opp = df_team_h['team_v']
    df_team_h = df_team_h[home_cols]
    df_team_h.columns = home_cols_stripped
    df_team_h['home_game'] = 1
    df_team_h['opponent'] = opp
    
    df_team = pd.concat((df_team_h, df_team_v))
    df_team.sort_values(['date_dblhead'], inplace=True)
    
    for winsize in windows:
        suff = str(winsize)
        for raw_col in ['AB', 'H', 'x2B', 'x3B', 'HR', 'BB', 'runs', 'SB', 'CS', 'ERR']:
            new_col = 'rollsum_' + raw_col + '_' + suff
            df_team[new_col] = df_team[raw_col].rolling(winsize, closed='left').sum()
        
        df_team['rollsum_BATAVG_' + suff] = df_team['rollsum_H_' + suff] / df_team['rollsum_AB_' + suff]
        df_team['rollsum_OBP_' + suff] = (df_team['rollsum_H_' + suff] + df_team['rollsum_BB_' + suff]) / (
            df_team['rollsum_BB_' + suff] + df_team['rollsum_AB_' + suff])
        df_team['rollsum_SLG_' + suff] = (df_team['rollsum_H_' + suff] + df_team['rollsum_x2B_' + suff] + 
                                         2 * df_team['rollsum_x3B_' + suff] + 3 * df_team['rollsum_HR_' + suff]) / (
                                         df_team['rollsum_AB_' + suff])
        df_team['rollsum_OBS_' + suff] = df_team['rollsum_OBP_' + suff] + df_team['rollsum_SLG_' + suff]
        
    df_team.set_index('date_dblhead', inplace=True)
    return df_team

In [34]:
df_nats = create_team_df('WAS')
df_nats.sample(10)

,day_of_week,team,league,runs,num_outs,day_night,park_id,attendance,duration,AB,H,x2B,x3B,HR,RBI,sac_hits,sac_flies,HBP,BB,IBB,K,SB,CS,GDP,CI,LOB,num_pitchers,IER,ER,WP,balks,PO,assists,ERR,PB,x2P,x3P,ump_home_id,ump_first_id,ump_second_id,ump_third_id,ump_lf_id,ump_rf_id,manager,starting_pitcher_id,starting_pitcher_name,visiting_2_id.1,batter1_id,batter1_name,batter1_pos,batter2_id,batter2_name,batter2_pos,batter3_id,batter3_name,batter3_pos,batter4_id,batter4_name,batter4_pos,batter5_id,batter5_name,batter5_pos,batter6_id,batter6_name,batter6_pos,batter7_id,batter7_name,batter7_pos,batter8_id,batter8_name,batter8_pos,batter9_id,batter9_name,batter9_pos,season,run_diff,home_victory,run_total,home_game,opponent,rollsum_AB_162,rollsum_H_162,rollsum_x2B_162,rollsum_x3B_162,rollsum_HR_162,rollsum_BB_162,rollsum_runs_162,rollsum_SB_162,rollsum_CS_162,rollsum_ERR_162,rollsum_BATAVG_162,rollsum_OBP_162,rollsum_SLG_162,rollsum_OBS_162,rollsum_AB_90,rollsum_H_90,rollsum_x2B_90,rollsum_x3B_90,rollsum_HR_90,rollsum_BB_90,rollsum_runs_90,rollsum_SB_90,rollsum_CS_90,rollsum_ERR_90,rollsum_BATAVG_90,rollsum_OBP_90,rollsum_SLG_90,rollsum_OBS_90,rollsum_AB_30,rollsum_H_30,rollsum_x2B_30,rollsum_x3B_30,rollsum_HR_30,rollsum_BB_30,rollsum_runs_30,rollsum_SB_30,rollsum_CS_30,rollsum_ERR_30,rollsum_BATAVG_30,rollsum_OBP_30,rollsum_SLG_30,rollsum_OBS_30
date_dblhead,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
201504110,Sat,WAS,NL,2,58,N,PHI13,23740.0,205,36,7,1,0,1,2,0,0,0,4,1,9,1,0,0,0,8,5,3,3,0,0,28,15,1,0,0,0,laynj901,wendh902,davib902,rackd901,NaN,NaN,willm003,fistd001,Doug Fister,harpb003,taylm002,Michael Taylor,8,escoy001,Yunel Escobar,5,NaN,Bryce Harper,9,zimmr001,Ryan Zimmerman,3,ramow001,Wilson Ramos,2,desmi001,Ian Desmond,6,johnr008,Reed Johnson,7,espid001,Danny Espinosa,4,fistd001,Doug Fister,1,2015,1,1,5,0,PHI,5524.0,1383.0,260.0,26.0,150.0,510.0,670.0,101.0,22.0,102.0,0.250362,0.313722,0.388306,0.702028,3052.0,784.0,149.0,12.0,89.0,289.0,386.0,59.0,17.0,49.0,0.256881,0.321161,0.401048,0.722210,1009.0,250.0,41.0,6.0,25.0,95.0,110.0,18.0,9.0,26.0,0.247770,0.312500,0.374628,0.687128
200607050,Wed,WAS,NL,9,54,N,WAS10,18441.0,198,38,15,5,0,0,9,0,1,0,4,0,8,0,1,2,0,7,6,17,17,1,0,27,12,1,0,1,0,fostm901,mcclt901,culbf901,welkb901,NaN,NaN,robif103,oconm001,Mike O'Connor,cabrm001,soria001,Alfonso Soriano,7,vidrj001,Jose Vidro,4,zimmr001,Ryan Zimmerman,5,johnn001,Nick Johnson,3,wardd002,Daryle Ward,9,clayr001,Royce Clayton,6,schnb001,Brian Schneider,2,byrdm001,Marlon Byrd,8,oconm001,Mike O'Connor,1,2006,-9,0,27,1,FLO,5470.0,1366.0,311.0,21.0,147.0,506.0,671.0,66.0,50.0,112.0,0.249726,0.313253,0.394881,0.708134,3054.0,784.0,180.0,9.0,98.0,301.0,409.0,52.0,31.0,66.0,0.256713,0.323398,0.417813,0.741211,1006.0,254.0,76.0,2.0,25.0,103.0,132.0,15.0,8.0,23.0,0.252485,0.321912,0.406561,0.728472
201606200,Mon,WAS,NL,1,51,N,LOS03,44712.0,170,34,7,1,0,0,1,0,0,0,0,0,10,0,0,0,0,6,3,4,4,0,0,24,8,0,0,1,0,blasc901,eddid901,nelsj901,lentn901,NaN,NaN,baked002,petiy001,Yusmeiro Petit,harpb003,taylm002,Michael Taylor,8,wertj001,Jayson Werth,7,NaN,Bryce Harper,9,murpd006,Daniel Murphy,4,zimmr001,Ryan Zimmerman,3,ramow001,Wilson Ramos,2,renda001,Anthony Rendon,5,espid001,Danny Espinosa,6,petiy001,Yusmeiro Petit,1,2016,3,1,5,0,LAN,5427.0,1346.0,253.0,14.0,199.0,566.0,717.0,73.0,26.0,71.0,0.248019,0.319039,0.409803,0.728842,3035.0,752.0,135.0,9.0,121.0,314.0,407.0,41.0,22.0,36.0,0.247776,0.318304,0.417792,0.736096,1019.0,269.0,44.0,4.0,49.0,87.0,157.0,18.0,9.0,11.0,0.263984,0.321881,0.459274,0.781154
201005050,Wed,WAS,NL,6,60,N,WAS11,15616.0,201,39,12,4,0,1,6,2,1,0,3,0,8,0,1,0,0,9,5,7,7,0,0,30,10,0,0,1,0,coope901,millb901,fairc901,reilm901,NaN,NaN,riggj801,atill001,Luis Atilano,jonec004,morgn001,Nyjer Morgan,8,kenna001,Adam Kennedy,4,zimmr001,Ryan Zimmerman,5,dunna001,Adam Dunn,3,rodri001,Ivan Rodriguez,2,harrw001,Willie Harris,7,desmi001,Ian Desmond,6,bernr001,Roger Bernadina,9,atill001,Luis Atilano,1,2010,-1,0,13,1,ATL,5450.0,1391.0,285.0,44.0,147.0,593.0,695.0,85.0,46.0,135.0,0.255229,0.328314,0.404587,0.732901,3023.0,761.0,158.0,30.0,87.0,327.0,400.0,55.0,27.0,68.0,0.251737,0.324776,0.410189,0.734965,1031.0,259.0,69.0,13.0,22.0,117.0,126.0,26.0,13.0,20.0,0.251212,0.327526,0.407371,0.734898
201809120,Wed,WAS,NL,5,54,N,PHI13,20258.0,176,35,9,3,0,3,5,0,0,0,1,0,9,0,0,1,0,4,3,1,1,0,0,27,5,0,0,0,0,wendh902,libkj901,drecb901,estam901,NaN,NaN,martd002,stras001,Stephen Strasburg,harpb003,eatoa002,Adam Eaton,9,turnt001,Trea Turner,6,NaN,Bryce Harper,8,renda001,Anthony Rendon,5,sotoj001,Juan Soto,7,zimmr001,Ryan Zimmerman,3,wietm001,Matt Wieters,2,difow001,Wilmer Difo,4,stras001,Stephen Strasburg,1,2018,-4,0,6,0,PHI,5496.0,1378.0,274.0,27.0,190.0,604.0,748.0,113.0,31.0,63.0,0.250728,0.324918,0.414119,0.739037,3081.0,795.0,154.0,16.0,98.0,333.0,436.0,61.0,16.0,30.0,0.258033,0.330404,0.413827,0.744231,1036.0,269.0,56.0,5.0,33.0,114.0,152.0,18.0,2.0,10.0,0.259653,0.333043,0.418919,0.751962
201205120,Sat,WAS,NL,2,54,N,CIN09,42294.0,188,31,6,1,0,2,2,1,0,0,5,1,11,2,0,1,0,8,3,1,1,0,0,27,5,0,1,1,0,coope901,fostm901,timmt901,kellj901,NaN,NaN,johnd105,zimmj003,Jordan Zimmermann,zimmr001,desmi001,Ian Desmond,6,bernr001,Roger Bernadina,7,NaN,Ryan Zimmerman,5,laroa001,Adam LaRoche,3,harpb003,Bryce Harper,9,espid001,Danny Espinosa,4,ankir001,Rick Ankiel,8,ramow001,Wilson Ramos,2,zimmj003,Jordan Zimmermann,1,2012,-1,0,3,0,CIN,5531.0,1354.0,275.0,20.0,155.0,482.0,624.0,97.0,39.0,101.0,0.244802,0.305338,0.385825,0.691164,3089.0,773.0,161.0,8.0,85.0,263.0,337.0,36.0,24.0,59.0,0.250243,0.309069,0.390094,0.699163,1020.0,245.0,57.0,2.0,23.0,100.0,104.0,13.0,9.0,19.0,0.240196,0.308036,0.367647,0.675683
201906110,Tue,WAS,NL,5,51,N,CHI12,16790.0,199,36,9,1,0,2,5,0,0,2,5,0,5,1,0,0,0,11,3,7,7,0,0,24,4,0,1,0,0,whitc901,rippm901,onorb901,kellj901,NaN,NaN,martd002,corbp001,Patrick Corbin,renda001,turnt001,Trea Turner,6,eatoa002,Adam Eaton,9,NaN,Anthony Rendon,5,sotoj001,Juan Soto,7,kendh001,Howie Kendrick,10,dozib001,Brian Dozier,4,gomey001,Yan Gomes,2,parrg001,Gerardo Parra,3,roblv001,Victor Robles,8,2019,2,1,12,0,CHA,5541.0,1443.0,295.0,26.0,197.0,611.0,809.0,101.0,31.0,80.0,0.260422,0.333875,0.429706,0.763581,3068.0,788.0,167.0,13.0,114.0,348.0,458.0,55.0,19.0,56.0,0.256845,0.332553,0.431226,0.763778,1009.0,265.0,63.0,6.0,37.0,100.0,157.0,11.0,7.0,18.0,0.262636,0.329125,0.446977,0.776103
201105240,Tue,WAS,NL,6,51,N,MIL06,24722.0,194,37,11,3,0,1,6,0,0,1,3,0,9,2,0,2,0,8,4,7,7,1,0,24,7,1,0,1,0,barkl901,johna901,culbf901,welkt901,NaN,NaN,riggj801,hernl003,Livan Hernandez,wertj001,bernr001,Roger Bernadina,8,desmi001,Ian Desmond,6,NaN,Jayson Werth,9,ramow001,Wilson Ramos,2,morsm001,Michael Morse,3,espid001,Danny Espinosa,4,hairj002,Jerry Hairston,5,bixlb001,Brian Bixler,7,hernl003,Livan Hernandez,1,2011,1,1,13,0,MIL,5405.0,1299.0,233.0,23.0,149.0,487.0,633.0,114.0,36.0,117.0,0.240333,0.303123,0.374653,0.677776,2997.0,697.0,130.0,14.0,76.0,294.0,357.0,59.0,21.0,59.0,0.232566,0.301124,0.361361,0.662486,1000.0,230.0,49.0,6.0,25.0,81.0,108.0,22.0,8.0,15.0,0.230000,0.287697,0.366000,0.653697
202104210,Wed,WAS,NL,1,51,D,WAS11,7769.0,181,28,4,2,0,0,1,0,0,0,2,0,5,1,0,1,0,5,4,0,0,0,0,27,4,0,0,2,0,rackd901,hudsm901,mosce901,vanol901,NaN,NaN,martd002,schem001,Max Scherzer,arenn001,steva001,Andrew Stevenson,9,harrj002,Josh Harrison,4,turnt001,Trea Turner,6,bellj005,Josh Bell,3,schwk001,Kyle Schwarber,7,casts001,Starlin Castro,5,avila001,Alex Avila,2,roblv001,Victor Robles,8,schem001,Max Scherzer,1,2021,1,1,1,1,SLN,5445.0,1467.0,308.0,28.0,206.0,573.0,849.0,114.0,32.0,86.0,0.269421,0.338983,0.449770,0.788753,2951.0,788.0,160.0,14.0,99.0,300.0,436.0,52.0,17.0,58.0,0.267028,0.334666,0.431379,0.766045,944.0,248.0,50.0,3.0,29.0,91.0,133.0,16.0,7.0,20.0,0.262712,0.327536,0.414195,0.741731
202106191,Sat,WAS,NL,1,42,D,WAS11,14434.0,167,24,4,1,0,0,1,0,0,1,7,0,8,1,0,1,0,10,3,5,5,0,0,21,8,1,0,1,0,hamaa901,may-b901,fairc901,danlk901,NaN,NaN,martd002,rossj002,Joe Ross,smitd008,schwk001,Kyle Schwarber,7,turnt001,Trea Turner,6,sotoj001,Juan Soto,9,bellj005,Josh Bell,3,harrj002,Josh Harrison,4,casts001,Starlin Castro,5,avila001,Alex Avila,2,roblv001,Victor Robles,8,rossj002,Joe Ross,1,2021,-4,0,6,1,NYN,5340.0,1382.0,277.0,23.0,180.0,519.0,746.0,87.0,30.0,94.0,0.258801,0.324458,0.420412,0.744870,2918.0,731.0,145.0,11.0,85.0,280.0,380.0,48.0,17.0,49.0,0.250514,0.316135,0.395134,0.711269,945.0,222.0,36.0,3.0,28.0,90.0,106.0,10.0,6.0,16.0,0.234921,0.301449,0.368254,0.669703

In [35]:
# Create team level dict for each team
team_data_dict = {}
for team in df.team_v.unique():
    team_data_dict[team] = create_team_df(team)

In [36]:
team_data_dict.keys()

dict_keys(['TOR', 'ATL', 'BAL', 'DET', 'BOS', 'MIN', 'NYA', 'LAN', 'CHN', 'SFN', 'PIT', 'CLE', 'MON', 'SEA', 'KCA', 'PHI', 'MIL', 'CIN', 'NYN', 'HOU', 'SLN', 'SDN', 'CHA', 'TEX', 'CAL', 'OAK', 'COL', 'FLO', 'ANA', 'TBA', 'ARI', 'WAS', 'MIA'])

In [37]:
## Create a variety of summarized statistics for each game
## For each game, we look up the home and visiting team in the team
## data dictionary, and then look up the game, and pull the relevant stats

stats = ['BATAVG', 'OBP', 'SLG', 'OBS', 'SB', 'CS', 'ERR']
teams = ['h', 'v']

# Initialize arrays
arrays = {f"{stat}_{window}_{team}": np.zeros(df.shape[0]) 
          for stat in stats for window in windows for team in teams}

# Populate the arrays
for i, (index, row) in enumerate(df.iterrows()):
    if i % 1000 == 0:
        print(i)
    
    home_team = row['team_h']
    visit_team = row['team_v']
    game_index = row['date_dblhead']
    
    for window in windows:
        for stat in stats:
            arrays[f'{stat}_{window}_h'][i] = team_data_dict[home_team].loc[game_index, f'rollsum_{stat}_{window}']
            arrays[f'{stat}_{window}_v'][i] = team_data_dict[visit_team].loc[game_index, f'rollsum_{stat}_{window}']

# Add arrays to DataFrame
for key, value in arrays.items():
    df[key] = value

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000

In [38]:
df.shape

(98704, 181)

In [39]:
df.sample(5)

,,day_of_week,team_v,league_v,team_h,league_h,runs_v,runs_h,num_outs,day_night,park_id,attendance,duration,AB_v,H_v,x2B_v,x3B_v,HR_v,RBI_v,sac_hits_v,sac_flies_v,HBP_v,BB_v,IBB_v,K_v,SB_v,CS_v,GDP_v,CI_v,LOB_v,num_pitchers_v,IER_v,ER_v,WP_v,balks_v,PO_v,assists_v,ERR_v,PB_v,x2P_v,x3P_v,AB_h,H_h,x2B_h,x3B_h,HR_h,RBI_h,sac_hits_h,sac_flies_h,HBP_h,BB_h,IBB_h,K_h,SB_h,CS_h,GDP_h,CI_h,LOB_h,num_pitchers_h,IER_h,ER_h,WP_h,balks_h,PO_h,assists_h,ERR_h,PB_h,x2P_h,x3P_h,ump_home_id,ump_first_id,ump_second_id,ump_third_id,ump_lf_id,ump_rf_id,manager_v,manager_h,starting_pitcher_id_v,starting_pitcher_name_v,starting_pitcher_id_h,starting_pitcher_name_h,batter1_id_v,batter1_name_v,batter1_pos_v,batter2_id_v,batter2_name_v,batter2_pos_v,visiting_2_id.1,batter3_name_v,batter3_pos_v,batter4_id_v,batter4_name_v,batter4_pos_v,batter5_id_v,batter5_name_v,batter5_pos_v,batter6_id_v,batter6_name_v,batter6_pos_v,batter7_id_v,batter7_name_v,batter7_pos_v,batter8_id_v,batter8_name_v,batter8_pos_v,batter9_id_v,batter9_name_v,batter9_pos_v,batter1_id_h,batter1_name_h,batter1_pos_h,batter2_id_h,batter2_name_h,batter2_pos_h,batter3_id_h,batter3_name_h,batter3_pos_h,batter4_id_h,batter4_name_h,batter4_pos_h,batter5_id_h,batter5_name_h,batter5_pos_h,batter6_id_h,batter6_name_h,batter6_pos_h,batter7_id_h,batter7_name_h,batter7_pos_h,batter8_id_h,batter8_name_h,batter8_pos_h,batter9_id_h,batter9_name_h,batter9_pos_h,season,run_diff,home_victory,run_total,date_dblhead,BATAVG_162_h,BATAVG_162_v,BATAVG_90_h,BATAVG_90_v,BATAVG_30_h,BATAVG_30_v,OBP_162_h,OBP_162_v,OBP_90_h,OBP_90_v,OBP_30_h,OBP_30_v,SLG_162_h,SLG_162_v,SLG_90_h,SLG_90_v,SLG_30_h,SLG_30_v,OBS_162_h,OBS_162_v,OBS_90_h,OBS_90_v,OBS_30_h,OBS_30_v,SB_162_h,SB_162_v,SB_90_h,SB_90_v,SB_30_h,SB_30_v,CS_162_h,CS_162_v,CS_90_h,CS_90_v,CS_30_h,CS_30_v,ERR_162_h,ERR_162_v,ERR_90_h,ERR_90_v,ERR_30_h,ERR_30_v
,Unnamed: 0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
35598,795,Thu,OAK,AL,TOR,AL,4,3,54,N,TOR02,30189.0,177,33,8,3,0,1,4,0,0,0,4,0,4,0,0,0,0,6,6,3,3,1,0,27,12,0,0,0,0,35,8,2,0,1,3,0,0,0,5,0,8,1,0,0,0,10,2,4,4,1,0,27,7,0,0,0,0,reilm901,younl901,garcr901,onorb901,NaN,NaN,howea001,gastc101,priea001,Ariel Prieto,hentp001,Pat Hentgen,mcdoj002,Jason McDonald,8,giamj001,Jason Giambi,7,berrg001,Geronimo Berroa,9,mcgwm001,Mark McGwire,3,cansj001,Jose Canseco,10,spies001,Scott Spiezio,4,bross001,Scott Brosius,5,willg002,George Williams,2,bourr001,Rafael Bournigal,6,nixoo001,Otis Nixon,8,merco002,Orlando Merced,9,cartj001,Joe Carter,7,sprae001,Ed Sprague,10,delgc001,Carlos Delgado,3,garcc001,Carlos Garcia,4,santb001,Benito Santiago,2,gonza001,Alex Gonzalez,6,britt001,Tilson Brito,5,1997,-1,0,7,199706050,0.251843,0.264580,0.245098,0.260239,0.248283,0.262343,0.311041,0.342239,0.300847,0.341750,0.297248,0.340830,0.401582,0.450391,0.373203,0.425347,0.375859,0.433688,0.712623,0.792630,0.674050,0.767097,0.673106,0.774519,134.0,69.0,76.0,41.0,23.0,11.0,41.0,33.0,29.0,20.0,8.0,5.0,101.0,105.0,42.0,60.0,16.0,22.0
23973,1533,Tue,SEA,AL,MIN,AL,5,10,51,N,MIN03,32090.0,172,32,9,3,0,1,5,1,1,0,2,0,8,0,0,2,0,4,5,10,10,3,0,24,12,0,0,2,0,34,12,1,2,0,8,0,0,1,6,0,6,1,0,2,0,7,2,3,3,0,0,27,16,1,0,2,0,phild901,cedeg901,hendt901,hirsj901,NaN,NaN,lefej101,kellt101,hanse001,Erik Hanson,erics001,Scott Erickson,marte001,Edgar Martinez,5,reynh001,Harold Reynolds,4,grifk002,Ken Griffey,8,obrip001,Pete O'Brien,3,buhnj001,Jay Buhner,9,brilg001,Greg Briley,7,davia002,Alvin Davis,10,vizqo001,Omar Vizquel,6,valld001,Dave Valle,2,gladd001,Dan Gladden,7,knobc001,Chuck Knoblauch,4,puckk001,Kirby Puckett,8,hrbek001,Kent Hrbek,3,davic001,Chili Davis,10,macks001,Shane Mack,9,paglm001,Mike Pagliarulo,5,ortij001,Junior Ortiz,2,newma001,Al Newman,6,1991,5,1,15,199108200,0.274602,0.255256,0.284709,0.252835,0.305451,0.277168,0.335322,0.327896,0.344474,0.319563,0.368376,0.340309,0.405572,0.378089,0.429623,0.384256,0.454887,0.429711,0.740894,0.705985,0.774096,0.703819,0.823263,0.770020,105.0,96.0,63.0,47.0,21.0,14.0,61.0,44.0,32.0,23.0,13.0,8.0,97.0,116.0,54.0,56.0,21.0,25.0
38410,1341,Sun,KCA,AL,CHA,AL,4,3,54,D,CHI12,32929.0,168,38,13,4,0,1,4,1,1,3,2,0,7,1,0,1,0,14,3,2,2,0,0,27,10,1,0,1,0,31,6,0,0,2,3,0,1,1,5,0,6,1,1,1,0,8,4,4,4,0,0,27,9,1,0,1,0,tscht901,brinj901,cedeg901,phild901,NaN,NaN,muset101,manuj101,ruscg001,Glendon Rusch,parqj001,Jim Parque,allej001,Jermaine Allensworth,8,offej001,Jose Offerman,4,macks001,Shane Mack,7,palmd002,Dean Palmer,5,kingj001,Jeff King,3,conij001,Jeff Conine,9,morrh001,Hal Morris,10,fasas001,Sal Fasano,2,lopem001,Mendy Lopez,6,durhr001,Ray Durham,4,snopc001,Chris Snopek,6,thomf001,Frank Thomas,10,bellj002,Albert Belle,7,ventr001,Robin Ventura,5,ordom001,Magglio Ordonez,9,cordw001,Wil Cordero,3,abboj002,Jeff Abbott,8,obric001,Charlie O'Brien,2,1998,-1,0,7,199807120,0.267235,0.262981,0.267642,0.263750,0.265761,0.273934,0.333718,0.323520,0.335105,0.317938,0.325913,0.322124,0.420174,0.407230,0.431545,0.399485,0.413191,0.410427,0.753892,0.730750,0.766650,0.717423,0.739104,0.732550,112.0,112.0,71.0,66.0,29.0,23.0,45.0,51.0,28.0,32.0,6.0,13.0,130.0,113.0,81.0,72.0,27.0,22.0
9889,71,Mon,CIN,NL,ATL,NL,9,8,54,N,ATL01,7404.0,171,38,13,1,0,1,9,2,0,1,5,0,7,0,0,0,0,10,4,5,5,0,0,27,9,3,0,0,0,42,13,3,0,1,7,0,0,0,2,0,4,0,0,0,0,9,5,9,9,0,0,27,12,0,0,0,0,quicj901,rungp901,palld901,engeb901,NaN,NaN,rosep001,haase101,stupj001,John Stuper,perep001,Pascual Perez,davie001,Eric Davis,8,rosep001,Pete Rose,3,parkd001,Dave Parker,9,cedec001,Cesar Cedeno,7,esasn001,Nick Esasky,5,concd001,Dave Concepcion,6,oestr001,Ron Oester,4,vangd001,Dave Van Gorder,2,stupj001,John Stuper,1,washc001,Claudell Washington,9,ramir001,Rafael Ramirez,6,kommb001,Brad Komminsk,7,murpd001,Dale Murphy,8,hornb001,Bob Horner,5,perrg001,Gerald Perry,3,ceror001,Rick Cerone,2,hubbg001,Glenn Hubbard,4,perep001,Pascual Perez,1,1985,-1,0,17,198504150,0.248712,0.242148,0.235137,0.244040,0.243402,0.249509,0.318311,0.312345,0.303316,0.311104,0.315044,0.314798,0.363870,0.351534,0.346359,0.350662,0.357771,0.352652,0.682181,0.663879,0.649675,0.661767,0.672816,0.667450,139.0,159.0,84.0,75.0,37.0,32.0,87.0,63.0,53.0,32.0,27.0,8.0,138.0,137.0,75.0,71.0,24.0,22.0
19517,1288,Wed,CAL,AL,OAK,AL,5,9,51,D,OAK01,44588.0,205,35,10,1,0,0,5,1,0,0,5,0,9,2,0,1,0,9,3,8,8,0,0,24,11,1,0,0,0,37,14,2,0,1,9,0,1,0,1,0,8,2,1,0,0,6,5,5,5,1,0,27,8,1,0,1,0,clara901,johnm901,phild901,reedr901,NaN,NaN,raded103,larut101,wittm001,Mike Witt,moorm001,Mike Moore,washc001,Claudell Washington,9,ray-j001,Johnny Ray,4,whitd001,Devon White,8,joynw001,Wally Joyner,3,downb001,Brian Downing,10,davic001,Chili Davis,7,schrb001,Bill Schroeder,2,howej002,Jack Howell,5,schod001,Dick Schofield,6,hendr001,Rickey Henderson,7,lansc001,Carney Lansford,5,parkd001,Dave Parker,10,mcgwm001,Mark McGwire,3,hendd001,Dave Henderson,8,cansj001,Jose Canseco,9,hassr001,Ron Hassey,2,philt001,Tony Phillips,4,gallm001,Mike Gallego,6,1989,4,1,14,198907260,0.268659,0.266797,0.265599,0.268128,0.260563,0.290200,0.339407,0.322687,0.333636,0.323100,0.343750,0.346760,0.396479,0.399929,0.382049,0.401547,0.367203,0.435775,0.735886,0.722616,0.715685,0.724647,0.710953,0.782536,137.0,88.0,73.0,51.0,27.0,12.0,56.0,44.0,32.0,25.0,14.0,12.0,112.0,112.0,74.0,52.0,27.0,17.0

In [ ]:
df.to_csv('data/df_mlb2.csv', index=False)

In [ ]:
df['home_victory'].mean()